### ISSUE TITLE
[feature request] Make rscope as a minor mode?

### ISSUE THREAD

**Issue by stardiviner** [rjarzmik/rscope#11]
It's better to port rscope into a minor mode?

**Comment by rjarzmik** [comment]
stardiviner <notifications@github.com> writes:

> It's better to port rscope into a minor mode?
Well, I don't find any good reason to do it.

What would be the rationale behind it ? Rscope is not specific to a buffer, it's
rather a general helper which looks at the current buffer to decide what should
be its answer.

I don't see what a minor mode would bring us, do you have something on mind ?

Cheers.

-- 
Robert

**Comment by stardiviner** [comment]
Reason:
for example, the global keymap prefix can't be undo, like in this situation: https://github.com/rjarzmik/rscope/issues/12 . If rscope is a minor mode, then it can be undone by disable rscope minor mode.
That's why I post this issue.

**Comment by rjarzmik** [comment]
I have a several usecases which make me think a minor user mode is not possible.
First I assume that a minor mode is a "per buffer" mode.

Now rscope has to be able to :
 - trigger a search from any file (a text file in linux-kernel/Documentation/XXX.txt)
 - autogenerate the rscope database from any file, without the minor mode being activated

I don't see how a minor mode would fit in this workflow. For me, the rscope should be usable all the time, from any file buffer.

**Comment by stardiviner** [comment]
I see. I agree on you openion.
