### ISSUE TITLE
It's not good to override [C-c s] in global keymap.

### ISSUE THREAD

**Issue by stardiviner** [rjarzmik/rscope#12]
I found rscope override global keymap [C-c s].
```lisp
(defun rscope:hook ()
  (global-set-key (kbd "\C-cs") 'rscope:map))

(add-hook 'c-mode-hook (function rscope:hook))
(add-hook 'c++-mode-hook (function rscope:hook))
(add-hook 'dired-mode-hook (function rscope:hook))
```

This really is not a good idea.
Because some user might bind key to `[C-c s]`.
I think add a customizable variable for keymap prefix is better.
the extension `projectile-rails` provide user to custom the keymap prefix.

**Comment by rjarzmik** [comment]
That's a good remark. Would you provide a patch ? :)

**Comment by rjarzmik** [comment]
I created a patch in "next" branch : "rscope: make the keyboard prefix customizable".
Is it the kind of patch you had in mind ?

**Comment by stardiviner** [comment]
I checked out the next branch, it can work.

**Comment by rjarzmik** [comment]
Integrated into master branch.
