### ISSUE TITLE
Need to do (require 'tramp) in rscope.el ?

### ISSUE THREAD

**Issue by Gaoithe** [rjarzmik/rscope#7]
To get it working I had to do a (require 'tramp) in my .emacs.
Should put (require 'tramp) into rscope.el I think.

In my .emacs:
(load "rscope.el")
(require 'tramp)
(require 'rscope)

**Comment by tpetazzoni** [comment]
This issue being fixed, maybe you can mark it as closed?

**Comment by rjarzmik** [comment]
Confirmed to work, closing.
